name: Game Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-vesion: 18.0.0
      - name: Install Dependencies
        run: npm i
      - name: Run The Server
        run: node server.js
